model_list:
  # Chat model 1
  - model_name: gemini/2.5-flash-lite
    litellm_params:
      custom_llm_provider: gemini
      model: gemini-2.5-flash-lite
      api_key: "AIzaSyCvVeRKAnhT5hv2ZnmvwA_nD6GDcEdP0Aw"
